# --- Categorization Rules ---
# Rules are processed in order. The first match wins.
# Each rule is a tuple: (list_of_keywords, category_name)
# All keywords in the list must be present in the memo (case-insensitive AND condition).
CATEGORIZATION_RULES = [
    # --- Highly Specific Payee/Transfer Rules (Revised for better Investment/Kaiubi logic) ---
    # Kaiubi Transfers SENT to specific Investment Institutions
    (['transferência enviada', 'kaiubi', 'xp invest'], ('Investimentos', 'Geral')),
    (['transferência enviada', 'kaiubi', 'easynvest'], ('Investimentos', 'Geral')),
    (['transferência enviada', 'kaiubi', 'banco c6'], ('Investimentos', 'Geral')),
    (['transferência enviada', 'kaiubi', 'caixa economica', 'cef'], ('Investimentos', 'Geral')),

    # Kaiubi Transfers RECEIVED from specific Investment Institutions
    (['transferência recebida', 'kaiubi', 'xp invest'], ('Investimentos', 'Geral')),
    (['transferência recebida', 'kaiubi', 'Banco XP S.A'], ('Investimentos', 'Geral')),
    (['transferência recebida', 'kaiubi', 'easynvest'], ('Investimentos', 'Geral')),

    (['transferência recebida', 'kaiubi', 'unibanco'], ('Renda', 'Salário')),


    # Specific Account Transfers (New)
    (['iti *kaiubi ferrei'], ('Transferência entre Contas', 'Geral')),

    # Other specific Investment institutions / transactions (New and Existing)
    (['banco topazio'], ('Investimentos', 'Geral')),
    (['remessa online'], ('Investimentos', 'Geral')),
    (['resgate fundo'], ('Investimentos', 'Geral')),
    (['aplicação rdb'], ('Investimentos', 'Geral')),
    (['resgate rdb'], ('Investimentos', 'Geral')),
    (['aplicação fundo'], ('Investimentos', 'Geral')),
    (['transferência de saldo nuinvest'], ('Investimentos', 'Geral')),
    (['saldo nuinvest'], ('Investimentos', 'Geral')),
    (['irrf sobre investimento'], ('Investimentos', 'Impostos')),

    # General Kaiubi Transfers (Fallbacks - Crucial for non-investment Kaiubi transfers like ITAU)
    (['transferência recebida', 'kaiubi'], ('Transferência entre Contas', 'Geral')),
    (['transferência enviada', 'kaiubi'], ('Transferência entre Contas', 'Geral')),
    (['leetcode'], ('Educação', 'Cursos')),

    # Financial - Loans & Specific Bank Transactions
    (['resgate de crédito pessoal'], ('Financeiro', 'Empréstimos')),
    (['credito pessoal'], ('Financeiro', 'Empréstimos')),
    (['depósito de crédito pessoal'], ('Financeiro', 'Empréstimos')),
    (['rewards - assinatura'], ('Financeiro', 'Cashback/Recompensas')),
    (['rewards assinatura'], ('Financeiro', 'Cashback/Recompensas')),
    (['rewards'], ('Financeiro', 'Cashback/Recompensas')),
    (['tarifa bancaria','tar-'], ('Financeiro', 'Tarifas Bancárias')),
    (['nubank ultravioleta - mensalidade'], ('Financeiro', 'Tarifas Bancárias')),
    (['saque'], ('Financeiro', 'Saque em Dinheiro')),
    (['transferencia doc'], ('Financeiro', 'Transferência Bancária')),
    (['ted'], ('Financeiro', 'Transferência Bancária')),
    (['transferencia ted'], ('Financeiro', 'Transferência Bancária')),

    # Specific Payees & Unique Transactions (New and Existing)
    (['tamires rodrigues de sousa'], ('Extraordinários', 'Casa')),
    (['tamires rodrigues de souza'], ('Extraordinários', 'Casa')),
    (['quality imoveis sp'], ('Moradia', 'Aluguel')),
    (['transferência recebida', 'pix', 'srf', 'irpf', '00.394.460/0058-87'], ('Financeiro', 'Restituição de Imposto')),
    (['secr. da receita federal'], ('Financeiro', 'Restituição de Imposto')),
    (['receita federal'], ('Financeiro', 'Restituição de Imposto')),
    (['zero berto car'], ('Extraordinários', 'Carro')),
    (['bruno ferreira fotog'], ('Extraordinários', 'Casamento')),
    (['pepper drinks'], ('Extraordinários', 'Casamento')),
    (['casa das aliancas'], ('Extraordinários', 'Casamento')),
    (['casa das alianças'], ('Extraordinários', 'Casamento')),
    (['vestire'], ('Extraordinários', 'Casamento')),
    (['atelier pamela'], ('Extraordinários', 'Casamento')),
    (['o rei dos convites comercial'], ('Extraordinários', 'Casamento')),
    (['espaço favoritto buffet'], ('Extraordinários', 'Casamento')),
    (['glenda carolina'], ('Extraordinários', 'Casamento')),
    (['solucoees em consultoria integradas'], ('Extraordinários', 'Casamento')),
    (['julio vieira'], ('Educação', 'Cursos')),
    (['sonho lar consultoria'], ('Moradia', 'Aluguel')),
    (['maria josé'], ('Moradia', 'Diarista')),
    (['quintoandar'], ('Moradia', 'Aluguel')),
    (['quinto andar'], ('Moradia', 'Aluguel')),
    (['amppy'], ('Moradia', 'Diarista')),
    (['dsobral'], ('Moradia', 'Reforma/Manutenção')),
    (['daniel valeriano sobral'], ('Moradia', 'Reforma/Manutenção')),
    (['vitor nocelli'], ('Moradia', 'Reforma/Manutenção')),
    (['argetax administracao'], ('Transporte', 'Combustível')),
    (['argetax'], ('Transporte', 'Combustível')),
    (['wise brasil'], ('Viagem', 'Câmbio de Moeda')),
    (['wise'], ('Viagem', 'Câmbio de Moeda')),
    (['western union'], ('Viagem', 'Câmbio de Moeda')),
    (['pet ltda'], ('Animais de Estimação', 'Geral')),
    (['porto pet'], ('Animais de Estimação', 'Geral')),
    (['medicapet'], ('Animais de Estimação', 'Geral')),
    (['animatrix'], ('Animais de Estimação', 'Geral')),


    # --- End of Highly Specific Payee/Transfer Rules ---

    # Travel (New and Existing - Grouped for clarity)
    (['hurb technologies'], ('Viagem', 'Geral')),
    (['hurb'], ('Viagem', 'Geral')),
    (['universal fl/lockers'], ('Viagem', 'Parques Temáticos/Atrações')),
    (['aerolinea'], ('Viagem', 'Voos')),
    (['lineas aereas'], ('Viagem', 'Voos')),
    (['lufthan'], ('Viagem', 'Voos')),
    (['civitatis'], ('Viagem', 'Passeios/Atividades')),
    (['decolar.com'], ('Viagem', 'Agências')),
    (['decolar'], ('Viagem', 'Agências')),
    (['omio'], ('Viagem', 'Agências')),
    (['cvc'], ('Viagem', 'Agências')),
    (['faroltur'], ('Viagem', 'Agências')),
    (['pousada'], ('Viagem', 'Hospedagem')),
    (['hotel'], ('Viagem', 'Hospedagem')),
    (['reserva do j'], ('Viagem', 'Hospedagem')),
    (['hoteis.com'], ('Viagem', 'Hospedagem')),
    (['hoteis com'], ('Viagem', 'Hospedagem')),
    (['booking.com'], ('Viagem', 'Hospedagem')),
    (['booking'], ('Viagem', 'Hospedagem')),
    (['airbnb'], ('Viagem', 'Hospedagem')),
    (['latam airlines'], ('Viagem', 'Voos')),
    (['latam'], ('Viagem', 'Voos')),
    (['azul linhas'], ('Viagem', 'Voos')),
    (['gol linhas'], ('Viagem', 'Voos')),
    (['patagonia'], ('Viagem', 'Passeios/Atividades')),
    (['kaliman'], ('Viagem', 'Passeios/Atividades')),
    (['clickbus'], ('Viagem', 'Ônibus')),
    (['guiche virtual'], ('Viagem', 'Ônibus')),
    (['guichê virtual'], ('Viagem', 'Ônibus')),
    (['souvenir'], ('Viagem', 'Lembrancinhas')),
    (['taxa de visto'], ('Viagem', 'Taxas/Vistos')),
    (['frango assado'], ('Viagem', 'Paradas de Estrada/Restaurantes')),
    (['aeropue'], ('Viagem', 'Voos')),
    (['kuar 1900'], ('Viagem', 'Hospedagem')),
    (['newton sampaio'], ('Viagem', 'Passeios/Atividades')),
    (['transferência enviada pelo pix - adrieli c dos santos'], ('Viagem', 'Despesas Compartilhadas')),
    (['transferência enviada pelo pix - leandro xavier borges'], ('Viagem', 'Despesas Compartilhadas')),

    # Entertainment (New and Existing - Grouped for clarity)
    (['ticketmaster'], ('Entretenimento', 'Ingressos')),
    (['tkt360'], ('Entretenimento', 'Ingressos')),
    (['steamgames.com'], ('Entretenimento', 'Jogos')),
    (['steam purchase'], ('Entretenimento', 'Jogos')),
    (['nuuvem'], ('Entretenimento', 'Jogos')),
    (['playstation'], ('Entretenimento', 'Jogos')),
    (['psn'], ('Entretenimento', 'Jogos')),
    (['xbox'], ('Entretenimento', 'Jogos')),
    (['microsoft store', 'xbox'], ('Entretenimento', 'Jogos')),
    (['microsoft store', 'game'], ('Entretenimento', 'Jogos')),
    (['pag*xsollagames'], ('Entretenimento', 'Jogos')),
    (['chess.com'], ('Entretenimento', 'Jogos')),
    (['epicgames'], ('Entretenimento', 'Jogos')),
    (['club madame'], ('Entretenimento', 'Bar/Casa Noturna')),
    (['baden baden'], ('Entretenimento', 'Bar/Casa Noturna')),
    (['dj club'], ('Entretenimento', 'Bar/Casa Noturna')),
    (['rock club'], ('Entretenimento', 'Bar/Casa Noturna')),
    (['pier 3'], ('Entretenimento', 'Bar/Casa Noturna')),
    (['arquidiocesana'], ('Entretenimento', 'Bar/Casa Noturna')),
    (['adega'], ('Entretenimento', 'Bar/Casa Noturna')),
    (['beer'], ('Entretenimento', 'Bar/Casa Noturna')),
    (['tokyo sp'], ('Entretenimento', 'Bar/Casa Noturna')),
    (['the blue pub'], ('Entretenimento', 'Bar/Casa Noturna')),
    (['divvino'], ('Entretenimento', 'Bar/Casa Noturna')),
    (['dica distribuidora'], ('Entretenimento', 'Bar/Casa Noturna')),
    (['comedy club'], ('Entretenimento', 'Bar/Casa Noturna')),
    (['comercio de bebid'], ('Entretenimento', 'Bar/Casa Noturna')),
    (['vila madalen'], ('Entretenimento', 'Bar/Casa Noturna')),
    (['kartodromo'], ('Entretenimento', 'Kart')),
    (['cinema'], ('Entretenimento', 'Cinema')),
    (['cinemark'], ('Entretenimento', 'Cinema')),
    (['uci'], ('Entretenimento', 'Cinema')),
    (['kinoplex'], ('Entretenimento', 'Cinema')),
    (['cinepolis'], ('Entretenimento', 'Cinema')),
    (['ingresso.com'], ('Entretenimento', 'Ingressos')),
    (['ingresso rapido'], ('Entretenimento', 'Ingressos')),
    (['ingressorap'], ('Entretenimento', 'Ingressos')),
    (['sympla'], ('Entretenimento', 'Ingressos')),
    (['teatro'], ('Entretenimento', 'Teatro/Shows')),
    (['osesp'], ('Entretenimento', 'Concertos/Orquestra')),

    # Specific Online Subscriptions & Services (Existing, with new additions)
    (['obsidian.md'], ('Serviços Online', 'Outros')),
    (['obsidian'], ('Serviços Online', 'Outros')),
    (['google a medium corp'], ('Serviços Online', 'Outros')),
    (['medium corp'], ('Serviços Online', 'Outros')),
    (['twitch'], ('Serviços Online', 'Outros')),
    (['audible'], ('Serviços Online', 'Outros')),
    (['pb*samsung'], ('Serviços Online', 'Outros')),
    (['patreonirel'], ('Serviços Online', 'Outros')),
    (['google chatgpt'], ('Serviços Online', 'Outros')),
    (['chatgpt'], ('Serviços Online', 'Outros')),
    (['google cloud'], ('Serviços Online', 'Outros')),
    (['google evernote'], ('Serviços Online', 'Outros')),
    (['google storage'], ('Serviços Online', 'Outros')),
    (['github.com'], ('Serviços Online', 'Outros')),
    (['linkedin'], ('Serviços', 'Assinatura Profissional')),
    (['linkedin premium'], ('Serviços', 'Assinatura Profissional')),
    (['dashlane'], ('Serviços', 'Gerenciador de Senhas')),
    (['trademap'], ('Serviços', 'Plataformas Financeiras')),
    (['mobills'], ('Serviços', 'Ferramentas Financeiras')),
    (['locaweb'], ('Serviços', 'Hospedagem Web/Domínio')),
    (['wix'], ('Serviços', 'Hospedagem Web/Domínio')),
    (['home assistant cloud'], ('Serviços', 'Assinatura de Nuvem')),
    (['microsoft*subscription'], ('Serviços', 'Software/Nuvem')),
    (['melimais'], ('Serviços', 'Assinatura Meli+')),
    (['meli+'], ('Serviços', 'Assinatura Meli+')),
    (['crunchyroll'], ('Serviços Online', 'Streaming')),
    (['curiositystream'], ('Serviços Online', 'Streaming')),
    (['spotify'], ('Serviços Online', 'Streaming')),
    (['netflix'], ('Serviços Online', 'Streaming')),
    (['globoplay'], ('Serviços Online', 'Streaming')),
    (['disneyplus'], ('Serviços Online', 'Streaming')),
    (['disney+'], ('Serviços Online', 'Streaming')),
    (['prime video'], ('Serviços Online', 'Streaming')),
    (['amazon prime', 'video'], ('Serviços Online', 'Streaming')),
    (['youtube', 'premium'], ('Serviços Online', 'Streaming')),
    (['google youtube'], ('Serviços Online', 'Streaming')),
    (['google play'], ('Serviços Online', 'Streaming')),
    (['youtube'], ('Serviços Online', 'Streaming')),
    (['hbo max'], ('Serviços Online', 'Streaming')),
    (['hbo'], ('Serviços Online', 'Streaming')),
    (['max', 'streaming'], ('Serviços Online', 'Streaming')),
    (['vimeo.com'], ('Serviços Online', 'Streaming')),
    (['xsolla'], ('Serviços Online', 'Streaming')),
    (['dramabox'], ('Serviços Online', 'Streaming')),
    (['coursera.org'], ('Educação', 'Geral')),
    (['coursera'], ('Educação', 'Geral')),
    (['coursra'], ('Educação', 'Geral')),
    (['udemy'], ('Educação', 'Geral')),
    (['musescore'], ('Educação', 'Aprendizado Musical')),
    (['pianomarvel'], ('Educação', 'Cursos')),
    (['algoexpert'], ('Educação', 'Cursos')),
    (['sunoresearch'], ('Educação', 'Cursos')),
    (['stoodi'], ('Educação', 'Cursos')),
    (['vox2you'], ('Educação', 'Cursos')),
    (['supesprof'], ('Educação', 'Cursos')),
    (['courses'], ('Educação', 'Cursos')),
    (['cursochurras'], ('Educação', 'Cursos')),

    # Online Marketplaces & General Online Purchases
    (['mercadolivre'], ('Compras (Geral)', 'Ecommerce')),
    (['mclivre'], ('Compras (Geral)', 'Ecommerce')),
    (['amazon.com.br'], ('Compras (Geral)', 'Ecommerce')),
    (['amazon marketplace'], ('Compras (Geral)', 'Ecommerce')),
    (['amazon'], ('Compras (Geral)', 'Ecommerce')),
    (['shopee'], ('Compras (Geral)', 'Ecommerce')),
    (['shein'], ('Compras (Geral)', 'Ecommerce')),
    (['aliexpress'], ('Compras (Geral)', 'Ecommerce')),
    (['ebay'], ('Compras (Geral)', 'Ecommerce')),
    (['alipaybrasil'], ('Compras (Geral)', 'Ecommerce')),
    (['alipay'], ('Compras (Geral)', 'Ecommerce')),
    (['wish.com'], ('Compras (Geral)', 'Ecommerce')),
    (['dx.com'], ('Compras (Geral)', 'Ecommerce')),
    (['americanas'], ('Compras (Geral)', 'Ecommerce')),
    (['submarino'], ('Compras (Geral)', 'Ecommerce')),
    (['kabum'], ('Compras (Geral)', 'Ecommerce')),
    (['magazine'], ('Compras (Geral)', 'Ecommerce')),
    (['magalu'], ('Compras (Geral)', 'Ecommerce')),
    (['dell'], ('Compras Online', 'Eletrônicos')),
    (['dafiti'], ('Compras (Geral)', 'Ecommerce')),
    (['extra.com'], ('Compras (Geral)', 'Ecommerce')),
    (['google play', 'google store'], ('Compras Online', 'Conteúdo Digital')),

    # Food & Dining
    (['degustaeventos'], ('Alimentação', 'Evento')),
    (['taste sao paulo'], ('Alimentação', 'Evento')),
    (['fiorella'], ('Alimentação', 'Diversos')),
    (['panificadora'], ('Alimentação', 'Diversos')),
    (['grao do ipiranga'], ('Alimentação', 'Diversos')),
    (['pao do parque'], ('Alimentação', 'Diversos')),
    (['paes'], ('Alimentação', 'Diversos')),
    (['la terrazza'], ('Alimentação', 'Restaurante/Delivery')),
    (['pata negra'], ('Alimentação', 'Restaurante/Delivery')),
    (['underdog'], ('Alimentação', 'Restaurante/Delivery')),
    (['pizza'], ('Alimentação', 'Restaurante/Delivery')),
    (['tempero de casa'], ('Alimentação', 'Restaurante/Delivery')),
    (['espeto'], ('Alimentação', 'Restaurante/Delivery')),
    (['cozinha'], ('Alimentação', 'Restaurante/Delivery')),
    (['dona marla'], ('Alimentação', 'Restaurante/Delivery')),
    (['churrasco'], ('Alimentação', 'Restaurante/Delivery')),
    (['madero'], ('Alimentação', 'Restaurante/Delivery')),
    (['santo dica'], ('Alimentação', 'Restaurante/Delivery')),
    (['feijao'], ('Alimentação', 'Restaurante/Delivery')),
    (['bella napoli'], ('Alimentação', 'Restaurante/Delivery')),
    (['arturito'], ('Alimentação', 'Restaurante/Delivery')),
    (['sushi'], ('Alimentação', 'Restaurante/Delivery')),
    (['hard rock cafe'], ('Alimentação', 'Restaurante/Delivery')),
    (['tratto'], ('Alimentação', 'Restaurante/Delivery')),
    (['serradomar'], ('Alimentação', 'Restaurante/Delivery')),
    (['taverna'], ('Alimentação', 'Restaurante/Delivery')),
    (['peixada'], ('Alimentação', 'Restaurante/Delivery')),
    (['chicken'], ('Alimentação', 'Restaurante/Delivery')),
    (['a casa do porco'], ('Alimentação', 'Restaurante/Delivery')),
    (['trem bom de minas'], ('Alimentação', 'Restaurante/Delivery')),
    (['vassoura quebrad'], ('Alimentação', 'Restaurante/Delivery')),
    (['dibaco'], ('Alimentação', 'Restaurante/Delivery')),
    (['villa grano'], ('Alimentação', 'Restaurante/Delivery')),
    (['abbraccio'], ('Alimentação', 'Restaurante/Delivery')),
    (['terraco'], ('Alimentação', 'Restaurante/Delivery')),
    (['waffle'], ('Alimentação', 'Restaurante/Delivery')),
    (['rest japones'], ('Alimentação', 'Restaurante/Delivery')),
    (['coco bambu'], ('Alimentação', 'Restaurante/Delivery')),
    (['garage sp'], ('Alimentação', 'Restaurante/Delivery')),
    (['marmitaria'], ('Alimentação', 'Restaurante/Delivery')),
    (['cantinho mineiro'], ('Alimentação', 'Restaurante/Delivery')),
    (['ifood'], ('Alimentação', 'Restaurante/Delivery')),
    (['ifd*'], ('Alimentação', 'Restaurante/Delivery')),
    (['rappi'], ('Alimentação', 'Restaurante/Delivery')),
    (['liv up'], ('Alimentação', 'Restaurante/Delivery')),
    (['ze delivery'], ('Alimentação', 'Restaurante/Delivery')),
    (['zé delivery'], ('Alimentação', 'Restaurante/Delivery')),
    (['mcdonalds'], ('Alimentação', 'Restaurante/Delivery')),
    (['mc donalds'], ('Alimentação', 'Restaurante/Delivery')),
    (['burger king'], ('Alimentação', 'Restaurante/Delivery')),
    (['bk'], ('Alimentação', 'Restaurante/Delivery')),
    (['burger'], ('Alimentação', 'Restaurante/Delivery')),
    (['hamburgueria'], ('Alimentação', 'Restaurante/Delivery')),
    (['habibs'], ('Alimentação', 'Restaurante/Delivery')),
    (["habib's"], ('Alimentação', 'Restaurante/Delivery')),
    (['outback'], ('Alimentação', 'Restaurante/Delivery')),
    (['r.c carbonell'], ('Alimentação', 'Restaurante/Delivery')),
    (['pag*icekombi'], ('Alimentação', 'Restaurante/Delivery')),
    (['petitartur'], ('Alimentação', 'Restaurante/Delivery')),
    (['petit artur'], ('Alimentação', 'Restaurante/Delivery')),
    (['si senor'], ('Alimentação', 'Restaurante/Delivery')),
    (['quiosque'], ('Alimentação', 'Restaurante/Delivery')),
    (['las chicas'], ('Alimentação', 'Restaurante/Delivery')),
    (['gastronomia'], ('Alimentação', 'Restaurante/Delivery')),
    (['emporio'], ('Alimentação', 'Restaurante/Delivery')),
    (['parrilla'], ('Alimentação', 'Restaurante/Delivery')),
    (['baccio'], ('Alimentação', 'Diversos')),
    (['bacio di latte'], ('Alimentação', 'Diversos')),
    (['sorvetes'], ('Alimentação', 'Diversos')),
    (['sorvete'], ('Alimentação', 'Diversos')),
    (['ice kombi'], ('Alimentação', 'Diversos')),
    (['cuor di crema'], ('Alimentação', 'Diversos')),
    (['starbucks'], ('Alimentação', 'Diversos')),
    (['pastel'], ('Alimentação', 'Diversos')),
    (['pasteis'], ('Alimentação', 'Diversos')),
    (['salgados'], ('Alimentação', 'Diversos')),
    (['acaraje'], ('Alimentação', 'Diversos')),
    (['lanchonete'], ('Alimentação', 'Diversos')),
    (['esfiha'], ('Alimentação', 'Diversos')),
    (['coffee'], ('Alimentação', 'Diversos')),
    (['coffe'], ('Alimentação', 'Diversos')),
    (['cafe', 'lanche'], ('Alimentação', 'Diversos')),
    (['padaria'], ('Alimentação', 'Diversos')),
    (['pan. e conf.'], ('Alimentação', 'Diversos')),
    (['restaurante'], ('Alimentação', 'Restaurante/Delivery')),
    (['restaurant'], ('Alimentação', 'Restaurante/Delivery')),
    (['food'], ('Alimentação', 'Restaurante/Delivery')),
    (['alimentacao'], ('Alimentação', 'Restaurante/Delivery')),
    (['alimentos'], ('Alimentação', 'Restaurante/Delivery')),
    (['bem alimentacao'], ('Alimentação', 'Restaurante/Delivery')),
    (['doces'], ('Alimentação', 'Diversos')),
    (['cafeteria'], ('Alimentação', 'Diversos')),
    (['bar'], ('Alimentação', 'Restaurante/Delivery')),

    # Groceries / Supermarket
    (['vila das frutas'], ('Alimentação', 'Supermercado')),
    (['peixaria'], ('Alimentação', 'Supermercado')),
    (['minuto pa'], ('Alimentação', 'Supermercado')),
    (['minuto pao de acucar'], ('Alimentação', 'Supermercado')),
    (['minuto pão de açúcar'], ('Alimentação', 'Supermercado')),
    (['da santa'], ('Alimentação', 'Supermercado')),
    (['hortifruti da santa'], ('Alimentação', 'Supermercado')),
    (['extra jaguare'], ('Alimentação', 'Supermercado')),
    (['extra jaguaré'], ('Alimentação', 'Supermercado')),
    (['cleumildes'], ('Alimentação', 'Supermercado')),
    (['smart break'], ('Alimentação', 'Supermercado')),
    (['inovakamura'], ('Alimentação', 'Supermercado')),
    (['frutas'], ('Alimentação', 'Supermercado')),
    (['frutaria'], ('Alimentação', 'Supermercado')),
    (['inovasanchez'], ('Alimentação', 'Supermercado')),
    (['dia brasil'], ('Alimentação', 'Supermercado')),
    (['supermercado'], ('Alimentação', 'Supermercado')),
    (['mercado'], ('Alimentação', 'Supermercado')),
    (['beef'], ('Alimentação', 'Supermercado')),
    (['carne'], ('Alimentação', 'Supermercado')),
    (['beef boutique'], ('Alimentação', 'Supermercado')),
    (['extra hiper'], ('Alimentação', 'Supermercado')),
    (['carrefour'], ('Alimentação', 'Supermercado')),
    (['pao de acucar'], ('Alimentação', 'Supermercado')),
    (['pão de açúcar'], ('Alimentação', 'Supermercado')),
    (['assai'], ('Alimentação', 'Supermercado')),
    (['assaí'], ('Alimentação', 'Supermercado')),
    (['atacadao'], ('Alimentação', 'Supermercado')),
    (['atacadão'], ('Alimentação', 'Supermercado')),
    (['sams club'], ('Alimentação', 'Supermercado')),
    (["sam's club"], ('Alimentação', 'Supermercado')),
    (['acougue'], ('Alimentação', 'Supermercado')),
    (['açougue'], ('Alimentação', 'Supermercado')),
    (['pag*comercialde'], ('Alimentação', 'Supermercado')),
    (['hirota'], ('Alimentação', 'Supermercado')),
    (['wal mart'], ('Alimentação', 'Supermercado')),
    (['walmart'], ('Alimentação', 'Supermercado')),
    (['bom beef'], ('Alimentação', 'Supermercado')),
    (['meet and fire'], ('Alimentação', 'Supermercado')),
    (['shopper'], ('Alimentação', 'Supermercado')),
    (['carnes'], ('Alimentação', 'Supermercado')),
    (['anaguma comercio de al'], ('Alimentação', 'Supermercado')),
    (['mini extra'], ('Alimentação', 'Supermercado')),
    (['bauducco'], ('Alimentação', 'Supermercado')),
    (['pescado'], ('Alimentação', 'Supermercado')),
    (['swift'], ('Alimentação', 'Supermercado')),
    (['swfit'], ('Alimentação', 'Supermercado')),
    (['tolezano'], ('Alimentação', 'Supermercado')),
    (['comercio de alime'], ('Alimentação', 'Supermercado')),
    (['superm'], ('Alimentação', 'Supermercado')),
    (['soberano festas'], ('Alimentação', 'Supermercado')),
    (['varejista'], ('Alimentação', 'Supermercado')),
    (['comercio de verdur'], ('Alimentação', 'Supermercado')),
    (['oxxo'], ('Alimentação', 'Supermercado')),


    # Transport
    (['localiza'], ('Transporte', 'Aluguel de Carro')),
    (['movida'], ('Transporte', 'Aluguel de Carro')),
    (['unidas', 'aluguel de carros'], ('Transporte', 'Aluguel de Carro')),
    (['rentalcars'], ('Transporte', 'Aluguel de Carro')),
    (['aluguel de carros'], ('Transporte', 'Aluguel de Carro')),
    (['uber'], ('Transporte', 'Aplicativo')),
    (['99app'], ('Transporte', 'Aplicativo')),
    (['99 taxi'], ('Transporte', 'Aplicativo')),
    (['cabify'], ('Transporte', 'Aplicativo')),
    (['nutag'], ('Transporte', 'Pedágios')),
    (['nu tag'], ('Transporte', 'Pedágios')),
    (['sem parar'], ('Transporte', 'Pedágios')),
    (['conectcar'], ('Transporte', 'Pedágios')),
    (['veloe'], ('Transporte', 'Pedágios')),
    (['bilhete unico'], ('Transporte', 'Transporte Público')),
    (['cartao top', 'cartão top'], ('Transporte', 'Transporte Público')),
    (['vamu'], ('Transporte', 'Transporte Público')),
    (['bilh unico'], ('Transporte', 'Transporte Público')),
    (['shellbox'], ('Transporte', 'Combustível')),
    (['shell box'], ('Transporte', 'Combustível')),
    (['ipiranga', 'combustivel'], ('Transporte', 'Combustível')),
    (['abastece ai'], ('Transporte', 'Combustível')),
    (['posto ipiranga'], ('Transporte', 'Combustível')),
    (['petrobras'], ('Transporte', 'Combustível')),
    (['posto br'], ('Transporte', 'Combustível')),
    (['rede campeao'], ('Transporte', 'Combustível')),
    (['posto'], ('Transporte', 'Combustível')),
    (['pag*jaguare'], ('Transporte', 'Combustível')),
    (['estacionament'], ('Transporte', 'Estacionamento')),
    (['estapar'], ('Transporte', 'Estacionamento')),
    (['mono nubank'], ('Transporte', 'Estacionamento')),
    (['tsusho'], ('Transporte', 'Manutenção Veicular')),
    (['centro automotivo'], ('Transporte', 'Manutenção Veicular')),
    (['allpark'], ('Transporte', 'Estacionamento')),
    (['multiplan administrado'], ('Transporte', 'Estacionamento')),
    (['multiplan'], ('Transporte', 'Estacionamento')),
    (['sao bernardo plaza'], ('Transporte', 'Estacionamento')),
    (['são bernardo plaza'], ('Transporte', 'Estacionamento')),
    (['park'], ('Transporte', 'Estacionamento')),
    (['principe humberto esta'], ('Transporte', 'Estacionamento')),
    (['shopping'], ('Transporte', 'Estacionamento')),
    (['marco zero'], ('Transporte', 'Estacionamento')),
    (['indigo'], ('Transporte', 'Estacionamento')),
    (['golden square'], ('Transporte', 'Estacionamento')),
    (['estaciona'], ('Transporte', 'Estacionamento')),
    (['andreense motos'], ('Transporte', 'Manutenção Veicular')),
    (['motorcycles'], ('Transporte', 'Manutenção Veicular')),
    (['propig *auto relampago'], ('Transporte', 'Manutenção Veicular')),
    (['auto relampago'], ('Transporte', 'Manutenção Veicular')),
    (['moto pecas'], ('Transporte', 'Manutenção Veicular')),
    (['lava rapido'], ('Transporte', 'Lava Rápido')),
    (['auto post'], ('Transporte', 'Combustível')),
    (['via independencia'], ('Transporte', 'Combustível')),

    # Utilities
    (['conta vivo'], ('Casa', 'Telefone/Internet')),
    (['vivo'], ('Casa', 'Telefone/Internet')),
    (['claro'], ('Casa', 'Telefone/Internet')),
    (['net servicos'], ('Casa', 'Telefone/Internet')),
    (['telefonica brasil'], ('Casa', 'Telefone/Internet')),
    (['enelsp'], ('Casa', 'Eletricidade')),
    (['enel'], ('Casa', 'Eletricidade')),
    (['light'], ('Casa', 'Eletricidade')),
    (['cpfl'], ('Casa', 'Eletricidade')),
    (['sabesp'], ('Casa', 'Água')),
    (['comgas'], ('Casa', 'Gás')),
    (['comgás'], ('Casa', 'Gás')),

    # Health & Wellness
    (['droga raia'], ('Saúde', 'Farmácia')),
    (['drogaraia'], ('Saúde', 'Farmácia')),
    (['raia'], ('Saúde', 'Farmácia')),
    (['drogasil'], ('Saúde', 'Farmácia')),
    (['pague menos'], ('Saúde', 'Farmácia')),
    (['ultrafarma'], ('Saúde', 'Farmácia')),
    (['drogaria são paulo'], ('Saúde', 'Farmácia')),
    (['drogaria sao paulo'], ('Saúde', 'Farmácia')),
    (['drogarias pacheco'], ('Saúde', 'Farmácia')),
    (['panvel'], ('Saúde', 'Farmácia')),
    (['farmacia', 'popular'], ('Saúde', 'Farmácia')),
    (['farmacia'], ('Saúde', 'Farmácia')),
    (['drogaria'], ('Saúde', 'Farmácia')),
    (['farma'], ('Saúde', 'Farmácia')),
    (['drog'], ('Saúde', 'Farmácia')),
    (['dragaria'], ('Saúde', 'Farmácia')),
    (['amil'], ('Saúde', 'Plano de Saúde')),
    (['unimed'], ('Saúde', 'Plano de Saúde')),
    (['bradesco saude'], ('Saúde', 'Plano de Saúde')),
    (['sulamerica saude'], ('Saúde', 'Plano de Saúde')),
    (['sulamérica saúde'], ('Saúde', 'Plano de Saúde')),
    (['clinica'], ('Saúde', 'Clínica/Consulta')),
    (['medicos'], ('Saúde', 'Clínica/Consulta')),
    (['consultoria medica'], ('Saúde', 'Clínica/Consulta')),
    (['smart fit'], ('Saúde', 'Academia')),
    (['smartfit'], ('Saúde', 'Academia')),
    (['bodytech'], ('Saúde', 'Academia')),
    (['bio ritmo'], ('Saúde', 'Academia')),
    (['aqua schoolac'], ('Saúde', 'Academia')),
    (['gympass'], ('Saúde', 'Academia')),
    (['wellhub'], ('Saúde', 'Academia')),
    (['academia'], ('Saúde', 'Academia')),
    (['crossfit'], ('Saúde', 'Academia')),
    (['freeletics'], ('Saúde', 'Academia')),
    (['bluefit'], ('Saúde', 'Academia')),
    (['redfit'], ('Saúde', 'Academia')),
    (['fitness22'], ('Saúde', 'Academia')),
    (['sanmer'], ('Saúde', 'Academia')),
    (['fleury'], ('Saúde', 'Laboratórios/Diagnósticos')),
    (['lavoisier'], ('Saúde', 'Laboratórios/Diagnósticos')),
    (['delboni auriemo', 'delboni'], ('Saúde', 'Laboratórios/Diagnósticos')),
    (['odontoclinic'], ('Saúde', 'Dentista')),
    (['sorridents'], ('Saúde', 'Dentista')),
    (['remedio'], ('Saúde', 'Farmácia')),
    (['suplemento'], ('Saúde', 'Suplementos')),

    # Pets
    (['melhorqgente'], ('Animais de Estimação', 'Geral')),
    (['melhor q gente'], ('Animais de Estimação', 'Geral')),
    (['petz'], ('Animais de Estimação', 'Geral')),
    (['cobasi'], ('Animais de Estimação', 'Geral')),
    (['petlove'], ('Animais de Estimação', 'Geral')),
    (['veterinario', 'veterinaria'], ('Animais de Estimação', 'Veterinário/Serviços Pet')),
    (['banho e tosa', 'pet shop banho'], ('Animais de Estimação', 'Veterinário/Serviços Pet')),
    (['hitpaw'], ('Serviços Online', 'Streaming')),
    (['health for pet'], ('Animais de Estimação', 'Veterinário/Serviços Pet')),
    (['pets'], ('Animais de Estimação', 'Geral')),
    (['pet center'], ('Animais de Estimação', 'Geral')),
    (['camarim da casa'], ('Moradia', 'Reforma/Manutenção')),
    (['nothingprojector'], ('Moradia', 'Reforma/Manutenção')),
    (['geniodesk'], ('Moradia', 'Reforma/Manutenção')),
    (['quadros e cia'], ('Moradia', 'Reforma/Manutenção')),
    (['madeiramadeir'], ('Moradia', 'Reforma/Manutenção')),
    (['panela de fe'], ('Moradia', 'Reforma/Manutenção')),
    (['artes'], ('Moradia', 'Reforma/Manutenção')),
    (['decoracao'], ('Moradia', 'Reforma/Manutenção')),
    (['sylvia design'], ('Moradia', 'Reforma/Manutenção')),
    (['vitrais'], ('Moradia', 'Reforma/Manutenção')),
    (['comfort center'], ('Moradia', 'Reforma/Manutenção')),
    (['daiso'], ('Compras (Geral)', 'Loja de Variedades')),
    (['imaginarium'], ('Pessoais', 'Presentes')),
    (['giuliana flores'], ('Compras (Geral)', 'Presentes/Flores')),
    (['puket'], ('Pessoais', 'Presentes')),
    (['buddha spa'], ('Pessoais', 'Presentes')),
    (['brinquedos'], ('Compras (Geral)', 'Brinquedos')),
    (['ar condicionado', 'compra'], ('Compras (Geral)', 'Eletrônicos/Casa')),
    (['ar condicionado', 'instalacao', 'instalação'], ('Moradia', 'Reforma/Manutenção')),
    (['ar condicionado', 'manutencao', 'manutenção'], ('Moradia', 'Reforma/Manutenção')),
    (['ar condicionado'], ('Moradia', 'Reforma/Manutenção')),
    (['tok&stok'], ('Moradia', 'Reforma/Manutenção')),
    (['tok stok'], ('Moradia', 'Reforma/Manutenção')),
    (['etna'], ('Moradia', 'Reforma/Manutenção')),
    (['camicado'], ('Moradia', 'Reforma/Manutenção')),
    (['c&a'], ('Pessoais', 'Roupas')),
    (['c&a modas'], ('Pessoais', 'Roupas')),
    (['cea pay'], ('Pessoais', 'Roupas')),
    (['renner'], ('Pessoais', 'Roupas')),
    (['lojas renner'], ('Pessoais', 'Roupas')),
    (['riachuelo'], ('Pessoais', 'Roupas')),
    (['zara'], ('Pessoais', 'Roupas')),
    (['via veneto'], ('Pessoais', 'Roupas')),
    (['polo'], ('Pessoais', 'Roupas')),
    (['planet girls'], ('Pessoais', 'Roupas')),
    (['decathlon'], ('Pessoais', 'Roupas')),
    (['centauro'], ('Pessoais', 'Roupas')),
    (['youcom'], ('Pessoais', 'Roupas')),
    (['lhetashop'], ('Pessoais', 'Roupas')),
    (['cea scs'], ('Pessoais', 'Roupas')),
    (['galeriadorock'], ('Pessoais', 'Roupas')),
    (['fashion'], ('Pessoais', 'Roupas')),
    (['fatto a mano'], ('Pessoais', 'Roupas')),
    (['khelf'], ('Pessoais', 'Roupas')),
    (['dudalina'], ('Pessoais', 'Roupas')),
    (['bayard esportes'], ('Pessoais', 'Roupas')),
    (['calcados'], ('Pessoais', 'Roupas')),
    (['instrumentos'], ('Compras (Geral)', 'Outros')),
    (['le postiche'], ('Compras (Geral)', 'Bolsas/Malas')),
    (['mens market'], ('Pessoais', 'Beleza')),
    (['cosmeticos'], ('Pessoais', 'Beleza')),
    (['loccitane'], ('Pessoais', 'Beleza')),
    (['bestgo'], ('Compras (Geral)', 'Eletrônicos/Acessórios')),
    (['otica solarium'], ('Compras (Geral)', 'Óculos/Ótica')),
    (['leroy merlin'], ('Moradia', 'Reforma/Manutenção')),
    (['telhanorte'], ('Moradia', 'Reforma/Manutenção')),
    (['telha norte'], ('Moradia', 'Reforma/Manutenção')),
    (['sodimac'], ('Moradia', 'Reforma/Manutenção')),
    (['c&c casa e construcao', 'c&c', 'cec'], ('Moradia', 'Reforma/Manutenção')),
    (['casa e construcao'], ('Moradia', 'Reforma/Manutenção')),
    (['material de construcao', 'material construcao'], ('Moradia', 'Reforma/Manutenção')),
    (['materiais de construc'], ('Moradia', 'Reforma/Manutenção')),
    (['casa da eletrica'], ('Moradia', 'Reforma/Manutenção')),
    (['casa do led'], ('Moradia', 'Reforma/Manutenção')),
    (['construdecor'], ('Moradia', 'Reforma/Manutenção')),
    (['livraria cultura'], ('Compras (Geral)', 'Livros')),
    (['saraiva'], ('Compras (Geral)', 'Livros')),
    (['ri happy'], ('Compras (Geral)', 'Brinquedos')),
    (['pbkids'], ('Compras (Geral)', 'Brinquedos')),
    (['le biscuit'], ('Compras (Geral)', 'Loja de Variedades')),
    (['studio'], ('Serviços', 'Barbearia')),

    # Insurance (Non-Health)
    (['tokio marine'], ('Transporte', 'Seguro auto')),
    (['porto seguro'], ('Transporte', 'Seguro auto')),
    (['bb seguros'], ('Transporte', 'Seguro Auto')),
    (['mapfre'], ('Transporte', 'Seguro Auto')),
    (['nu seguro celular'], ('Financeiro', 'Seguro Auto')),
    (['seguro celular'], ('Financeiro', 'Seguro celular')),
    (['celular seguro'], ('Financeiro', 'Seguro celular')),
    (['refugio do nobre'], ('Pessoais', 'Beleza')),
    (['refugio do n'], ('Pessoais', 'Beleza')),
    (['studio plaza prime'], ('Pessoais', 'Beleza')),
    (['seguro auto'], ('Transporte', 'Seguro auto')),

    # User-added rules (newly added section or append to existing logical group)
    (['nu cafe'], ('Alimentação', 'Restaurante/Delivery')),
    (['valet'], ('Transporte', 'Estacionamento')),
    (['anchieta grill'], ('Alimentação', 'Restaurante/Delivery')),
    (['deposito do paraiba'], ('Moradia', 'Reforma/Manutenção')),
    (['google ellation'], ('Serviços Online', 'Outros')),
    (['pix', 'aline maria souza da paz'], ('Moradia', 'Diarista')),
    (['openai'], ('Serviços Online', 'Outros')),


    # Generic terms (lower priority - ensure these are LAST or near last within their logical groups)
    (['compra'], ('Compras (Geral)', 'Ecommerce')),
    (['pagamento'], ('Serviços', 'Pagamentos')),
    (['pgto'], ('Serviços', 'Pagamentos')),
    (['pagto'], ('Serviços', 'Pagamentos')),
    (['iof'], ('Impostos e Taxas', 'Geral')),
    (['authentic feet'], ('Pessoais', 'Roupas')),
    (['vestuario'], ('Pessoais', 'Roupas')),
    (['gamestation'], ('Entretenimento', 'Jogos')),
    (['du chapeu'], ('Moradia', 'Reforma/Manutenção')),
    (['kalunga'], ('Compras (Geral)', 'Ecommerce')),
    (['antonio soares da silva'], ('Moradia', 'Reforma/Manutenção')),
    (['leandro kley'], ('Transporte', 'Manutenção Veicular')),
    (['dreamcomfort'], ('Moradia', 'Reforma/Manutenção')),
    (['gabrielle leithold'], ('Extraordinários', 'Casamento')),
    (['k rcher loja'], ('Moradia', 'Reforma/Manutenção')),
    (['inusual'], ('Moradia', 'Reforma/Manutenção')),
] 